### ISSUE TITLE
Header mit Anmelden/Abmelden

### ISSUE THREAD

**Issue by s0552107** [MfN-Berlin/mwSkinNaturkunde#24]
Der Header auf dem sich der An und Abmeldebutton und einig andere Elemente ist zu dunkel, oder die Schrift muss eine andere bekommen. Vielleicht standartmäßig weiß und mit hover MfN-Grün, oder ähnliches.

**Comment by alvarosaurus** [comment]
"Der Header ... ist zu dunkel" wontfix: das sind dieselben Farben als auf der Webseite.
