### ISSUE TITLE
Seiten-Buttons: Lesen, Bearbeiten, ...

### ISSUE THREAD

**Issue by s0552107** [MfN-Berlin/mwSkinNaturkunde#25]
Die Buttons Lesen, Bearbeiten, Quelltext bearbeiten, Versionsgeschichte, *Zahnräder* sind auf aktive Größer als die anderen Buttons. Desweiteren ist beim hovern über den Bereits ausgewählten Button eine Farbveränderung (leicht helleres Grün)  zu vernehmen. 
Wenn die jetzt feststeht, dass bei Hover der Button Weiß wird muss bei der Suche der Button auch noch so angepasst werden (und die Lupe wieder dunkel).
Seite    Diskussion sollten so eingestellt werden, dass das aktuell ausgewählte Dunkel und die andere Möglichkeit hell ist. Sonst könnte man das vertauschen.

Der button unter Versionsgeschichte : Gewählte Versionen vergleichen sollte ein Margin-Button bekommen.

**Comment by alvarosaurus** [comment]
"Die Buttons Lesen, Bearbeiten, ... sind auf aktive Größer als die anderen Buttons" done

"beim hovern über den Bereits ausgewählten Button ... leicht helleres Grün" done

"die Lupe wieder dunkel" done

"Seite Diskussion sollten so eingestellt werden, dass das aktuell ausgewählte Dunkel und die andere Möglichkeit hell ist." done

"Gewählte Versionen vergleichen sollte ein Margin-Button bekommen." done
