### ISSUE TITLE
Projektseiten 

### ISSUE THREAD

**Issue by s0552107** [MfN-Berlin/mwSkinNaturkunde#26]
Bei Lesen befindet sich oben unter der Überschrift unbestimmtes Fenster. Was ist das? 

Die Überlick ... Leiste
Das active : grau ist anders als das background grau, wenn ich mich nicht täusche. Ich bin mir aber nicht sicher. Ich würde den kasten aber auch über die ganze Höhe machen. 
Wenn Überblick ausgewählt ist sieht es komisch aus wenn unten Links noch die Border-Buttom zu sehen ist, wie ein Pixelfehler oder so. Also auch ein bisschen Breiter.

Überlick-Schrift ist immer Grün, nicht nur beim hovern

**Comment by alvarosaurus** [comment]
"Unbestimmtes Fenster": kann ich nicht reproduzieren. Vielleicht nur bei bestimmte Projekte? Oder die Vorlage ist veraltet? Aktualisiere bitte die Testdaten.
