### ISSUE TITLE
Navigationsleiste Links

### ISSUE THREAD

**Issue by s0552107** [MfN-Berlin/mwSkinNaturkunde#27]
Beim Hovern in Navigation und Werkzeuge ist fast über die komplette Seite unterschrichen und auch mit mehr Abstand zur schrift. 

Im Inhaltsverzeichnis ist es direkt unter der Schrift aber auch nur die breite der Schrift.

Für eins von beiden sollte sich entschieden werden.

**Comment by alvarosaurus** [comment]
Kann ich nicht reproduzieren. Links werdennicht unterstrichen.
